NAME
  ParaView::IOVisItBridge
LIBRARY_NAME
  vtkIOVisItBridge
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) 2000 - 2020, Lawrence Livermore National Security, LLC
  Copyright (c) Kitware Inc.
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright © Tech-X Corporation
LICENSE_FILES
  ../LICENSE
DEPENDS
  VTK::CommonCore
  VTK::CommonExecutionModel
PRIVATE_DEPENDS
  ParaView::VisItLib
  VTK::CommonDataModel
  VTK::CommonMisc
  VTK::CommonSystem
  VTK::CommonTransforms
  VTK::FiltersAMR
  VTK::FiltersCore
  VTK::IOGeometry
  VTK::IOImage
  VTK::IOLegacy
  VTK::IOParallel
  VTK::ImagingCore
  VTK::ParallelCore
  VTK::hdf5
  VTK::netcdf
  VTK::zlib
OPTIONAL_DEPENDS
  VTK::mpi
